version: '2'
services:
  web:
    image: prayr/nginx
    volumes:
      - .:/srv/app
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    image: prayr/php-fpm
    volumes:
      - .:/srv/app
    depends_on:
      - mysql
      - redis
    environment:
      SYMFONY_ENV: dev
      SYMFONY_DATABASE_HOST: mysql
      SYMFONY_DATABASE_NAME: prayr_dev
      SYMFONY_DATABASE_USER: prayr
      SYMFONY_DATABASE_PASSWORD: prayr

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: prayr_dev
      MYSQL_USER: prayr
      MYSQL_PASSWORD: prayr
      MYSQL_ROOT_PASSWORD: miau
    ports:
      - "3306:3306"
  redis:
      image: redis:3
