parameters:
#    parameter_name: value

services:
  app.twig_asset_version_extension:
    class: AppBundle\Twig\AssetVersionExtension
    arguments: ["%kernel.root_dir%"]
    tags:
      - { name: twig.extension }
